### ISSUE TITLE
Not specific

### ISSUE THREAD

**Issue by Netroxen** [Swassie/BF4-EE-Tool#1]
You don't specify which lamp is number 1? Only that they should be entered from 1-20... Maybe you could reiterate over this and specify where to start... Using a 'NE' type naming convention would work. That is unless, you can start from any position?

**Comment by Netroxen** [comment]
Having not watched the video I can realise the confusion here. Just thought I would point it out, of course if you watch it then it'll make sense. Otherwise the script has worked flawlessly, well done!

**Comment by Swassie** [comment]
Hey, thanks for your comment! I know that the documentation is poor, I didn't have time to write any details before going away for the holidays. About the lamp number issue you can use whatever number rule you want, as long as you use the same rule for all buttons. The one in the video is just an example. I'm glad it worked for you!
